<?php


/**
 * Skeleton subclass for performing query and update operations on the 'oai_data_provider' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Nov 11 12:36:26 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.dcOAIServiceProviderPlugin.lib.model
 */
class oaiDataProviderPeer extends BaseoaiDataProviderPeer
{
  /**
   * Retrieve every oaiDataProvider object that is enabled.
   *
   * @param  Criteria  $criteria Optional criteria.
   * @param  PropelPDO $con      Optional PDO object.
   *
   * @return array oaiDataProvider[]
   */
  static public function retrieveEnabled(Criteria $criteria = null, PropelPDO $con = null)
  {
    if (null === $criteria)
    {
      $criteria = new Criteria();
    }

    $criteria->add(self::IS_ENABLED, true);

    return self::doSelect($criteria, $con);
  }

  /**
   * Retrieve an oaiDataProvider object by its url.
   *
   * @param  string $url    Desired url.
   * @param  PropelPDO $con Optional PDO object.
   *
   * @return oaiDataProvider
   */
  static public function retrieveByUrl($url, PropelPDO $con = null)
  {
    $criteria = new Criteria();

    $criteria->add(self::URL, $url);

    return self::doSelectOne($criteria, $con);
  }

} // oaiDataProviderPeer
