<?php


/**
 * Skeleton subclass for representing a row from the 'oai_harvested_data' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Nov 11 14:03:55 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.dcOAIServiceProviderPlugin.lib.model
 */
class oaiHarvestedData extends BaseoaiHarvestedData {

} // oaiHarvestedData
